General:
    comment: efficientnet-b5, msunet, copy from model017, add rotate180
    seed: 42
    multi_gpu_mode: ddp
    n_gpus: 1
    epoch: 10
    debug: True

Data:
    dataset:
        train_df: ../input/train.pkl
        test_df: ../input/test.pkl
        text_col: textDisplay
        target_col: resB_label
        fold: 0
        max_token_len: 512
    dataloader:
        batch_size: 16
        num_workers: 8

Model:
    name: BERTClassifier
    params:
        pretrained_model: cl-tohoku/bert-base-japanese-char-whole-word-masking
        n_classes: 5

Optimizer:
    optimizer: 
        name: AdamW
        lr: !!python/float 1e-6
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: 30
            eta_min: !!python/float 1e-5
            last_epoch: -1

Loss:
    name: CrossEntropyLoss